language: ruby
cache: bundler

rvm:
  - 2.2.3

before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 23114c8dd28080bf13ed2d6e4aad43b5f7b23cceee0f4a7b40d3cdd3384b179f

services:
  - postgresql
